@API_HostAddress = http://localhost:5132

### Add Order and OrderDetails
POST {{API_HostAddress}}/api/Orders HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "CustomerID": "3d6dc92a-6a71-48d0-a09e-811f1a7133de",
    "OrderDetails": [
        {
            "ProductId": "01444e9a-ba89-46c1-9ba4-37cc7413695c",
            "Quantity": 2,
            "UnitPrice": 10.00
        },
        {
            "ProductId": "01444e9a-ba89-46c1-9ba4-37cc7413695c",
            "Quantity": 1,
            "UnitPrice": 15.00
        }
    ]
}
### Get Order
Get {{API_HostAddress}}/api/Orders/37e33bbb-96e4-435a-835a-3e076754907d HTTP/1.1
Accept: application/json
Content-Type: application/json

### Get Orders
Get {{API_HostAddress}}/api/Orders HTTP/1.1
Accept: application/json
Content-Type: application/json

### Update an Order
PUT {{API_HostAddress}}/api/Orders/37e33bbb-96e4-435a-835a-3e076754907d HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "ID_Order": "37e33bbb-96e4-435a-835a-3e076754907d",
    "CustomerID": "3d6dc92a-6a71-48d0-a09e-811f1a7133de",
    "TotalAmount": 100.00,
    "Status": "Shipped"
}

### Delete an Order
DELETE {{API_HostAddress}}/api/orders/37e33bbb-96e4-435a-835a-3e076754907d HTTP/1.1

### Options for Orders
OPTIONS {{API_HostAddress}}/api/orders HTTP/1.1