// <auto-generated />
using System;
using DBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241016122854_UnitCreat")]
    partial class UnitCreat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBase.Models.Products", b =>
                {
                    b.Property<Guid>("Id_Product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Auto"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id_Product");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id_Product = new Guid("84519a35-02b2-49ce-bac6-9119456a08c8"),
                            Auto = 0,
                            ProductName = "холодильник",
                            UnitPrice = 100m
                        },
                        new
                        {
                            Id_Product = new Guid("d98e7b27-e0b5-4fae-a41e-db3be037c890"),
                            Auto = 0,
                            ProductName = "рыба",
                            UnitPrice = 40m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
